# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhorton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ht',
            name='basis',
            field=models.CharField(default='STO-3G', max_length=20),
        ),
        migrations.AlterField(
            model_name='ht',
            name='scf',
            field=models.CharField(default='plain_scf', max_length=20),
        ),
    ]
