# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhorton', '0002_auto_20160401_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ht',
            name='alpha',
        ),
        migrations.RemoveField(
            model_name='ht',
            name='basis',
        ),
        migrations.RemoveField(
            model_name='ht',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='ht',
            name='scf',
        ),
        migrations.AddField(
            model_name='ht',
            name='input_script',
            field=models.FileField(null=True, upload_to='horton/input'),
        ),
        migrations.AddField(
            model_name='ht',
            name='output_script',
            field=models.FileField(null=True, upload_to='horton/output'),
        ),
    ]
