# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactant', models.FileField(upload_to='')),
                ('product', models.FileField(upload_to='')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('auto_ic', models.BooleanField()),
            ],
        ),
    ]
