# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ts',
            name='auto_ic',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='ts',
            name='ratio',
            field=models.CharField(max_length=5),
        ),
    ]
