# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160331_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='ts',
            name='product',
            field=models.FileField(null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='ts',
            name='reactant',
            field=models.FileField(null=True, upload_to='reactant/'),
        ),
        migrations.AlterField(
            model_name='ts',
            name='auto_ic',
            field=models.CharField(default='on', max_length=3),
        ),
        migrations.AlterField(
            model_name='ts',
            name='ratio',
            field=models.CharField(default='0.50', max_length=5),
        ),
    ]
